export const skillsData = [
  {skill: 'UI'},
  {skill: '.NET'},
  {skill: 'Java'},
  {skill: 'Full stack web developer'},
  {skill: 'PHP'},
  {skill: 'Python'},
  {skill: 'Go'},
  {skill: 'Redis'},
  {skill: 'Postgres'},
  {skill: 'UX'},
  {skill: 'AWS'},
  {skill: 'HTML'},
  {skill: 'CSS'},
  {skill: 'Angular'},
  {skill: 'React'},
  {skill: 'JVM'},
  {skill: 'Android'},
  {skill: 'IOS'},
]; 